### ISSUE TITLE
iterable.length deprecated when using with ImmutableJS

### ISSUE THREAD

**Issue by suzuki11109** [substack/tape#239]
I got a warning when I tried to deepEqual with immutable data. It said about .length is deprecated.
Here is the message.
```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Map.Object.defineProperty.get (/Users/akisuzuki/Developments/tape_immutable/node_modules/immutable/dist/immutable.js:4650:21)
    at isBuffer (/Users/akisuzuki/Developments/tape_immutable/node_modules/deep-equal/index.js:35:46)
    at objEquiv (/Users/akisuzuki/Developments/tape_immutable/node_modules/deep-equal/index.js:59:7)
    at module.exports (/Users/akisuzuki/Developments/tape_immutable/node_modules/deep-equal/index.js:26:12)
    at Test.deepEqual.Test.deepEquals.Test.isEquivalent.Test.same (/Users/akisuzuki/Developments/tape_immutable/node_modules/tape/lib/test.js:373:18)
    at Test.bound [as deepEqual] (/Users/akisuzuki/Developments/tape_immutable/node_modules/tape/lib/test.js:61:32)
    at Test.<anonymous> (/Users/akisuzuki/Developments/tape_immutable/test.js:7:5)
    at Test.bound [as _cb] (/Users/akisuzuki/Developments/tape_immutable/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/akisuzuki/Developments/tape_immutable/node_modules/tape/lib/test.js:77:10)
    at Test.bound [as run] (/Users/akisuzuki/Developments/tape_immutable/node_modules/tape/lib/test.js:61:32)
```
and the test code.
```
var test = require('tape');
var Immutable = require('immutable');

test('test', function(t) {
  var map1 = Immutable.Map({a:1, b:2, c:3});
  var map2 = Immutable.Map({a:1, b:2, c:3});
  t.deepEqual(map1, map2);
  t.end();
});
```

Thanks.

**Comment by ljharb** [comment]
`t.deepEqual` follows `assert.deepEqual` - when using Immutable, I think you'll either have to ignore the warning, or, convert them to a normal object (or an array of entries) before comparing, or, use comparison functions that Immutable provides.

**Comment by suzuki11109** [comment]
I see. I've tried  `t.ok(Immutable.is(map1, map2));` and it pass without warning.
Thanks again.

**Comment by sainthkh** [comment]
I've created the project [`tape for immutable`](https://github.com/sainthkh/tape-for-immutable) for this.
