### ISSUE TITLE
Capturing TAP plan to be printed to a file

### ISSUE THREAD

**Issue by choonchernlim** [substack/tape#246]
My goal is to pipe the TAP output into a file so that I can use Jenkins' TAP plugin to display the test report.

Based on your doc, I have the following `test/index.js`:-

	import glob from 'glob';
	import test from 'tape';
	import path from 'path';
	import fs from 'fs';

	const stream = test.createStream();
	const reportStream = fs.createWriteStream( 'reports/tap.txt' );

	// display TAP output in console
	stream.pipe( process.stdout );

	// save TAP output to file
	stream.pipe( reportStream );

	// require all tests
	glob.sync( '../test/**/*.spec.js', { realpath : true, cwd : __dirname } ).forEach( require );

When I execute `tape -r babel-register tests/index.js`, I get the generated file:-

	TAP version 13
	# my test
	ok 1 given undefined, should be abc
	ok 2 given a value, should be xyz
	ok 3 given a value, should be xyz111

When I run my Jenkins job, I'm getting this exception:-

	org.tap4j.parser.ParserException: Error parsing TAP Stream: Missing TAP Plan.
		at org.tap4j.parser.Tap13Parser.parse(Tap13Parser.java:221)
		at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:187)

After digging out, it appears the generated file is missing the TAP plan, which is `1..3`.

I decided to hardcode `1..3` to that file, and it works great in Jenkins.

	TAP version 13
	# my test
	ok 1 given undefined, should be abc
	ok 2 given a value, should be xyz
	ok 3 given a value, should be xyz111
	1..3
	
My question to you is.... how exactly do I capture the number of assertions from Tape so that I can add this additional line to my `test/index.js`?

	// how to compute "totalAssertions" in test/index.js?
	reportStream.write('1..' + totalAssertions + '\n');

Thank you very much.

**Comment by choonchernlim** [comment]
I just realized that executing the tests itself does indeed print the TAP plan (`1..3`) in the generated file.

However, when I execute isparta to perform code coverage (`babel-node node_modules/isparta/bin/isparta cover --report cobertura --dir reports/coverage test/index.js`), the TAP plan goes missing, presumably `Results.close()` didn't get call to output the count.

Sorry about the confusion.
