### ISSUE TITLE
Tape hangs when testing server startup

### ISSUE THREAD

**Issue by fergiemcdowall** [substack/tape#263]
When testing "start server" scenarios on Restify and Norch, Tape tests dont compete, they just hang.

Example:

```javascript
var restify = require('restify')
var server = restify.createServer()
var tape = require('tape')

test('timing test', function (t) {
  t.plan(1)
  server.listen(8080, function() {
    t.equal(1, 1)
    console.log('%s listening at %s', server.name, server.url)
  })
})
```

Are there any magic tricks or special incantations to get this to work? Am I just doing it wrong? If so, what is the correct way of doing it?

**Comment by substack** [comment]
``` js
var restify = require('restify')
var server = restify.createServer()
var tape = require('tape')

test('timing test', function (t) {
  t.plan(1)
  t.once('end', function () { server.close() })
  server.listen(8080, function() {
    t.equal(1, 1)
    console.log('%s listening at %s', server.name, server.url)
  })
})
```

or

``` js
var restify = require('restify')
var server = restify.createServer()
var tape = require('tape')

test('timing test', function (t) {
  t.plan(1)
  server.listen(8080, function() {
    t.equal(1, 1)
    console.log('%s listening at %s', server.name, server.url)
  })
})

test('teardown', function (t) {
  server.close()
  t.end()
})
```

**Comment by fergiemcdowall** [comment]
cheers!

**Comment by bennypowers** [comment]
Tried the above pattern and got:

```
TypeError: this._emitCloseIfDrained is not a function
  ---
    operator: fail
    at: Server.<anonymous> (/Users/bennyp/Documents/test.js:95:9)
    stack: |-
      Error: TypeError: this._emitCloseIfDrained is not a function
          at Test.assert [as _assert] (/Users/bennyp/Documents/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/bennyp/Documents/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/Users/bennyp/Documentsnode_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/Users/bennyp/Documents/node_modules/tape/lib/test.js:77:32)
          at Server.<anonymous> (/Users/bennyp/Documents/test.js:95:9)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:118:7)
  ...
```
