### ISSUE TITLE
TypeError: Cannot convert null to object

### ISSUE THREAD

**Issue by dcousens** [substack/tape#324]
Just noticed the following error at [the end of one of my node `0.10` builds](https://travis-ci.org/dcousens/typeforce/jobs/163967349).

``` js
/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:449
        if (!isEnumerable(err, 'message') || !has(err, 'message')) {
             ^
TypeError: Cannot convert null to object
    at propertyIsEnumerable (native)
    at Test.throws (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:449:14)
    at Test.bound [as throws] (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:65:32)
    at Test.<anonymous> (/home/travis/build/dcousens/typeforce/test/index.js:39:7)
    at Test.bound [as _cb] (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:65:32)
    at Test.run (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:84:10)
    at Test.bound [as run] (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/test.js:65:32)
    at Object.next [as _onImmediate] (/home/travis/build/dcousens/typeforce/node_modules/tape/lib/results.js:71:15)
```

**Comment by ljharb** [comment]
crap, thanks, will fix

**Comment by dcousens** [comment]
Interesting,  does that mean I threw a `null`?  D:

**Comment by ljharb** [comment]
Yep, that is what it means
