### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by mjasnikovs** [substack/tape#390]
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
        at _addListener (events.js:281:19)
        at process.addListener (events.js:298:10)
        at module.exports.callback (c:\hub\aizkraukle-server\src\databases\createPino.js:11:10)
        at Array.cb (c:\hub\aizkraukle-server\src\app.js:44:9)
        at parallel (c:\hub\aizkraukle-server\node_modules\scpp\index.js:12:11)
        at module.exports.callback (c:\hub\aizkraukle-server\src\app.js:40:2)
        at Test.t (c:\hub\aizkraukle-server\test\user\userSubscription.test.js:89:2)
        at Test.bound [as _cb] (c:\hub\aizkraukle-server\node_modules\tape\lib\test.js:64:32)
        at Test.run (c:\hub\aizkraukle-server\node_modules\tape\lib\test.js:83:10)
        at Test.bound [as run] (c:\hub\aizkraukle-server\node_modules\tape\lib\test.js:64:32)
```

I think this should throw an appropriate error. It's confusing now.
If you require more information, I can debug. Or try to make a reproducible case. 
Pleas let me know.
4.8.0
node: 8.3.0

**Comment by ljharb** [comment]
This is a warning that comes from node itself; and it's coming from inside your own code.

You can pass a flag to node to alter the threshold; you can ignore the warning; or you can fix your code to not have more than 10 listeners on the same emitter simultaneously.
