### ISSUE TITLE
failure doesn't produce stacks if actual value is falsy

### ISSUE THREAD

**Issue by nhamer** [substack/tape#399]
https://github.com/substack/tape/blob/b66f8f80928bb82f0817407880a139ad118daf01/lib/results.js#L160

    test('failureStacks', function(t) {
      t.equal(true, false); // returns a full stack
      t.equal(false, true); // no stack
      t.end();
    });

**Comment by ljharb** [comment]
What do you mean by "stack" here? Error objects have stacks; not assertions.

**Comment by nhamer** [comment]
Sorry for the imprecision - I mean the output of the above test is:

TAP version 13
# failureStacks
not ok 1 should be equal
  ---
    operator: equal
    expected: false
    actual:   true
    at: Test.<anonymous> (c:\myproj\test.js:3:5)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (c:\myproj\node_modules\tape\lib\test.js:212:54)
          at Test.bound [as _assert] (c:\myproj\node_modules\tape\lib\test.js:64:32)
          at Test.equal.Test.equals.Test.isEqual.Test.is.Test.strictEqual.Test.strictEquals (c:\myproj\node_modules\tape\lib\test.js:347:10)
          at Test.bound (c:\myproj\node_modules\tape\lib\test.js:64:32)
          at Test.<anonymous> (c:\myproj\test.js:3:5)
          at Test.bound [as _cb] (c:\myproj\node_modules\tape\lib\test.js:64:32)
          at Test.run (c:\myproj\node_modules\tape\lib\test.js:83:10)
          at Test.bound [as run] (c:\myproj\node_modules\tape\lib\test.js:64:32)
          at Immediate.next (c:\myproj\node_modules\tape\lib\results.js:71:15)
          at runCallback (timers.js:672:20)
  ...
not ok 2 should be equal
  ---
    operator: equal
    expected: true
    actual:   false
    at: Test.<anonymous> (c:\myproj\test.js:4:5)
  ...

1..2
# tests 2
# pass  0
# fail  2
