### ISSUE TITLE
question: how do i see the msg when things fail.

### ISSUE THREAD

**Issue by simbo1905** [substack/tape#474]
If I have:

```
t.equals(jsY, jY), `not same eval for ${i}, jsY: ${jsY}, jY: ${jY}`;
```

All I see as output is: 

```
not ok 4 should be equal
  ---
    operator: equal
    expected: |-
      -71
    actual: |-
      185
    at: Test.<anonymous> (/Users/Shared/shamir/src/test/js/PolygotTests.js:151:7)
    stack: |-
      Error: should be equal
          at Test.assert (/Users/Shared/shamir/node_modules/tape/lib/test.js:241:54)
          at Test.bound (/Users/Shared/shamir/node_modules/tape/lib/test.js:92:28)
          at Test.equal (/Users/Shared/shamir/node_modules/tape/lib/test.js:401:10)
          at Test.bound (/Users/Shared/shamir/node_modules/tape/lib/test.js:92:28)
          at Test.<anonymous> (/Users/Shared/shamir/src/test/js/PolygotTests.js:151:7)
          at Test.bound (/Users/Shared/shamir/node_modules/tape/lib/test.js:92:28)
          at Test.run (/Users/Shared/shamir/node_modules/tape/lib/test.js:111:10)
          at Test.bound (/Users/Shared/shamir/node_modules/tape/lib/test.js:92:28)
          at Immediate.next (/Users/Shared/shamir/node_modules/tape/lib/results.js:90:19)
          at runCallback (timers.js:705:18)
  ...
```

How can I see the msg field that I add to my calls to tap?

I am using `"tape": "^4.10.2"`

**Comment by ljharb** [comment]
You're not passing the message into `t.equals` there - you're using the comma operator, so it's like:
```js
t.equals(jsY, jY);
`not same eval for ${i}, jsY: ${jsY}, jY: ${jY}`;
```

put it inside the parens.
