### ISSUE TITLE
test using setTimeout breaking in v5.0.0

### ISSUE THREAD

**Issue by rvillane** [substack/tape#509]
Using v4.x.x the following test passed just fine

```
    test('refreshExpiredCache happy path', async t => {
        const emptyMap = new Map();
        // empties out the current data
        sut.setAll(Constants.CacheType.DIRSHP_SKU, emptyMap);
        sut.refreshExpiredCache(Constants.CacheType.DIRSHP_SKU, emptyMap);

        // waits 5 seconds before continuing the validation to that refreshExpiredCache has finished
        const timer = setTimeout(() => {
            const dirShipSkuValuesObj = sut.getAll(Constants.CacheType.DIRSHP_SKU);
            t.equals(Object.keys(dirShipSkuValuesObj).length, 1, '1 entry expected');
            t.equals(Object.keys(dirShipSkuValuesObj)[0], '004G210000', 'first refreshed key');
            clearTimeout(timer);
            t.end();
        }, 5000);
    });
```

but after updating to v5.0.0 is failing with the following error on each assertion without the setTimeout callback function

```
not ok 41 .end() already called: 1 entry expected
  ---
    operator: fail
    at: Timeout.setTimeout [as _onTimeout] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/tests/domain-cache-query-manager-test.js:149:15)
    stack: |-
      Error: .end() already called: 1 entry expected
          at Test.assert [as _assert] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:260:54)
          at Test.bound [as _assert] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:84:32)
          at Test.fail (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:354:10)
          at Test.bound [as fail] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:84:32)
          at Test.assert [as _assert] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:238:14)
          at Test.bound [as _assert] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:84:32)
          at Test.strictEqual (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:424:10)
          at Test.bound [as equals] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/node_modules/tape/lib/test.js:84:32)
          at Timeout.setTimeout [as _onTimeout] (/Users/crmar/GitHub_Storage/order-services-domain-data-image/tests/domain-cache-query-manager-test.js:149:15)
          at ontimeout (timers.js:425:11)
          at tryOnTimeout (timers.js:289:5)
          at listOnTimeout (timers.js:252:5)
          at Timer.processTimers (timers.js:212:10)
```

Any suggestion about what needs to be refactored on the test case ?

**Comment by ljharb** [comment]
In this case, your test function is an `async function`, so it returns a promise. This means that your choices are either 1) don't use `async` here, since you're not using `await`, or:
```js
return new Promise((resolve) => {
  setTimeout(() => {
        resolve();
    }, 5000);
}).then(() => {
    const dirShipSkuValuesObj = sut.getAll(Constants.CacheType.DIRSHP_SKU);
    t.equals(Object.keys(dirShipSkuValuesObj).length, 1, '1 entry expected');
    t.equals(Object.keys(dirShipSkuValuesObj)[0], '004G210000', 'first refreshed key');
});
```
(note that you don't need the `clearTimeout`, since the timer has been used by the time your timer function runs)

**Comment by rvillane** [comment]
nice, removing async made the trick.

thanks for the assistance
